<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Quiz extends \App\Entity\Quiz implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'Title', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'date_quiz', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'Category', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'random', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'questions', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'public', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'publicResult'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'Title', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'date_quiz', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'Category', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'random', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'questions', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'public', '' . "\0" . 'App\\Entity\\Quiz' . "\0" . 'publicResult'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Quiz $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(?string $Title): \App\Entity\Quiz
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$Title]);

        return parent::setTitle($Title);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateQuiz(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateQuiz', []);

        return parent::getDateQuiz();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateQuiz(?\DateTimeInterface $date_quiz): \App\Entity\Quiz
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateQuiz', [$date_quiz]);

        return parent::setDateQuiz($date_quiz);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(?string $image): \App\Entity\Quiz
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory(): ?\App\Entity\Category
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(?\App\Entity\Category $Category): \App\Entity\Quiz
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$Category]);

        return parent::setCategory($Category);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\Quiz
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getRandom(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRandom', []);

        return parent::getRandom();
    }

    /**
     * {@inheritDoc}
     */
    public function setRandom(?bool $random): \App\Entity\Quiz
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRandom', [$random]);

        return parent::setRandom($random);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuestions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuestions', []);

        return parent::getQuestions();
    }

    /**
     * {@inheritDoc}
     */
    public function addQuestion(\App\Entity\Question $question): \App\Entity\Quiz
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addQuestion', [$question]);

        return parent::addQuestion($question);
    }

    /**
     * {@inheritDoc}
     */
    public function removeQuestion(\App\Entity\Question $question): \App\Entity\Quiz
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeQuestion', [$question]);

        return parent::removeQuestion($question);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublic(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublic', []);

        return parent::getPublic();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublic(?bool $public): \App\Entity\Quiz
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublic', [$public]);

        return parent::setPublic($public);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublicResult(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublicResult', []);

        return parent::getPublicResult();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublicResult(?bool $publicResult): \App\Entity\Quiz
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublicResult', [$publicResult]);

        return parent::setPublicResult($publicResult);
    }

}
