<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWsk6Z2b\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWsk6Z2b/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWsk6Z2b.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWsk6Z2b\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWsk6Z2b\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Wsk6Z2b',
    'container.build_id' => '3eaad28b',
    'container.build_time' => 1626008928,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWsk6Z2b');
