<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSWhHckZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSWhHckZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSWhHckZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSWhHckZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSWhHckZ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SWhHckZ',
    'container.build_id' => 'a5cc9577',
    'container.build_time' => 1625227668,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSWhHckZ');
