<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7ISxxJP\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7ISxxJP/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7ISxxJP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7ISxxJP\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container7ISxxJP\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '7ISxxJP',
    'container.build_id' => '15380d03',
    'container.build_time' => 1625235948,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7ISxxJP');
